version: '3'
networks:
  jira-network:
services:
  node1:
    image: atlassian/jira-software:8.5.0
    container_name: node1
    restart: unless-stopped
    networks:
      - jira-network
    volumes:
      - ./jira-home-node1:/var/atlassian/application-data/jira
      - ./jira-shared-home:/var/atlassian/jira-shared-home
    ports:
      - 8080:8080
    environment:
      - CATALINA_CONTEXT_PATH=/jd
      - CATALINA_OPTS="-Datlassian.cluster.scale=true -DjvmRoute=node1"
      - ATL_JDBC_URL=jdbc:postgresql://database:5432/jiradb
      - ATL_JDBC_USER=postgres
      - ATL_JDBC_PASSWORD=1234
      - ATL_DB_DRIVER=org.postgresql.Driver
      - ATL_DB_TYPE=postgres72
      # Data Center configuration
      - CLUSTERED=true
      - JIRA_NODE_ID=node1
      - EHCACHE_LISTENER_HOSTNAME=node1
      - EHCACHE_LISTENER_PORT=40001
      - EHCACHE_OBJECT_PORT=40011
      - EHCACHE_PEER_DISCOVERY=default      
      # Home Directories
      - JIRA_HOME=/var/atlassian/application-data/jira
      - JIRA_SHARED_HOME=/var/atlassian/jira-shared-home
    depends_on:
      - database
    links:
      - database
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/jd"]
      interval: 5m
      timeout: 10s
  node2:
    image: atlassian/jira-software:8.5.0
    container_name: node2
    restart: unless-stopped
    networks:
      - jira-network
    volumes:
      - ./jira-home-node1:/var/atlassian/application-data/jira
      - ./jira-shared-home:/var/atlassian/jira-shared-home
    ports:
      - 8080:8080
    environment:
      - CATALINA_CONTEXT_PATH=/jd
      - CATALINA_OPTS="-Datlassian.cluster.scale=true -DjvmRoute=node2"
      - ATL_JDBC_URL=jdbc:postgresql://database:5432/jiradb
      - ATL_JDBC_USER=postgres
      - ATL_JDBC_PASSWORD=1234
      - ATL_DB_DRIVER=org.postgresql.Driver
      - ATL_DB_TYPE=postgres72
      # Data Center configuration
      - CLUSTERED=true
      - JIRA_NODE_ID=node2
      - EHCACHE_LISTENER_HOSTNAME=node2
      - EHCACHE_LISTENER_PORT=40001
      - EHCACHE_OBJECT_PORT=40011
      - EHCACHE_PEER_DISCOVERY=default      
      # Home Directories
      - JIRA_HOME=/var/atlassian/application-data/jira
      - JIRA_SHARED_HOME=/var/atlassian/jira-shared-home
    depends_on:
      - database
    links:
      - database
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/jd"]
      interval: 5m
      timeout: 10s
  database:
    image: postgres:9.6
    container_name: database
    volumes:
    - ./postgresql-data:/var/lib/postgresql/data
    - ./postgre-db-init.sql:/docker-entrypoint-initdb.d/postgre-db-init.sql
    ports:
      - 5432:5432
    networks:
      - jira-network
    environment:
      POSTGRES_PASSWORD: 1234
